---
# tasks file for common
- name: install packages
  apt: name={{item}} state=present
  with_items:
       - default-jdk
       - mc
       - htop
       - maven
       - tmux
       - tomcat9
       - git